allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  fallow: true
  inotify: false
  msw: true
  sharp: true
  unrs-resolver: true
# pnpm bug ERR_PNPM_MISSING_TIME https://github.com/pnpm/pnpm/issues/11597
# minimumReleaseAge: 1440
resolutionMode: lowest-direct
