#!/usr/bin/env bash
pnpm pre || exit 1
# abort the commit if tanstack start has decided to replace a route file with a template
# batgrep messes with ripgrep's exit code
$(which rg) -F 'return <div>Hello ' && exit 1
exit 0