/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as uiRouteRouteImport } from './routes/(ui)/route'
import { Route as uiIndexRouteImport } from './routes/(ui)/index'
import { Route as IconSplatRouteImport } from './routes/icon/$'
import { Route as ApiSseRouteImport } from './routes/api/sse'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiActionRouteImport } from './routes/api/action'
import { Route as uiUnitsRouteImport } from './routes/(ui)/units'
import { Route as uiItemsRouteImport } from './routes/(ui)/items'
import { Route as uiHistoryRouteImport } from './routes/(ui)/history'
import { Route as uiCategoriesRouteImport } from './routes/(ui)/categories'
import { Route as ApiStatusChar123HashChar125RouteImport } from './routes/api/status/{-$hash}'

const uiRouteRoute = uiRouteRouteImport.update({
  id: '/(ui)',
  getParentRoute: () => rootRouteImport,
} as any)
const uiIndexRoute = uiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => uiRouteRoute,
} as any)
const IconSplatRoute = IconSplatRouteImport.update({
  id: '/icon/$',
  path: '/icon/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSseRoute = ApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)
const uiUnitsRoute = uiUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiItemsRoute = uiItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiHistoryRoute = uiHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiCategoriesRoute = uiCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => uiRouteRoute,
} as any)
const ApiStatusChar123HashChar125Route =
  ApiStatusChar123HashChar125RouteImport.update({
    id: '/api/status/{-$hash}',
    path: '/api/status/{-$hash}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/categories': typeof uiCategoriesRoute
  '/history': typeof uiHistoryRoute
  '/items': typeof uiItemsRoute
  '/units': typeof uiUnitsRoute
  '/api/action': typeof ApiActionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/icon/$': typeof IconSplatRoute
  '/': typeof uiIndexRoute
  '/api/status/{-$hash}': typeof ApiStatusChar123HashChar125Route
}
export interface FileRoutesByTo {
  '/categories': typeof uiCategoriesRoute
  '/history': typeof uiHistoryRoute
  '/items': typeof uiItemsRoute
  '/units': typeof uiUnitsRoute
  '/api/action': typeof ApiActionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/icon/$': typeof IconSplatRoute
  '/': typeof uiIndexRoute
  '/api/status/{-$hash}': typeof ApiStatusChar123HashChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(ui)': typeof uiRouteRouteWithChildren
  '/(ui)/categories': typeof uiCategoriesRoute
  '/(ui)/history': typeof uiHistoryRoute
  '/(ui)/items': typeof uiItemsRoute
  '/(ui)/units': typeof uiUnitsRoute
  '/api/action': typeof ApiActionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/icon/$': typeof IconSplatRoute
  '/(ui)/': typeof uiIndexRoute
  '/api/status/{-$hash}': typeof ApiStatusChar123HashChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/categories'
    | '/history'
    | '/items'
    | '/units'
    | '/api/action'
    | '/api/ping'
    | '/api/sse'
    | '/icon/$'
    | '/'
    | '/api/status/{-$hash}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/categories'
    | '/history'
    | '/items'
    | '/units'
    | '/api/action'
    | '/api/ping'
    | '/api/sse'
    | '/icon/$'
    | '/'
    | '/api/status/{-$hash}'
  id:
    | '__root__'
    | '/(ui)'
    | '/(ui)/categories'
    | '/(ui)/history'
    | '/(ui)/items'
    | '/(ui)/units'
    | '/api/action'
    | '/api/ping'
    | '/api/sse'
    | '/icon/$'
    | '/(ui)/'
    | '/api/status/{-$hash}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  uiRouteRoute: typeof uiRouteRouteWithChildren
  ApiActionRoute: typeof ApiActionRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSseRoute: typeof ApiSseRoute
  IconSplatRoute: typeof IconSplatRoute
  ApiStatusChar123HashChar125Route: typeof ApiStatusChar123HashChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(ui)': {
      id: '/(ui)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof uiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ui)/': {
      id: '/(ui)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof uiIndexRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/icon/$': {
      id: '/icon/$'
      path: '/icon/$'
      fullPath: '/icon/$'
      preLoaderRoute: typeof IconSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sse': {
      id: '/api/sse'
      path: '/api/sse'
      fullPath: '/api/sse'
      preLoaderRoute: typeof ApiSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ui)/units': {
      id: '/(ui)/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof uiUnitsRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/items': {
      id: '/(ui)/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof uiItemsRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/history': {
      id: '/(ui)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof uiHistoryRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/categories': {
      id: '/(ui)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof uiCategoriesRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/api/status/{-$hash}': {
      id: '/api/status/{-$hash}'
      path: '/api/status/{-$hash}'
      fullPath: '/api/status/{-$hash}'
      preLoaderRoute: typeof ApiStatusChar123HashChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface uiRouteRouteChildren {
  uiCategoriesRoute: typeof uiCategoriesRoute
  uiHistoryRoute: typeof uiHistoryRoute
  uiItemsRoute: typeof uiItemsRoute
  uiUnitsRoute: typeof uiUnitsRoute
  uiIndexRoute: typeof uiIndexRoute
}

const uiRouteRouteChildren: uiRouteRouteChildren = {
  uiCategoriesRoute: uiCategoriesRoute,
  uiHistoryRoute: uiHistoryRoute,
  uiItemsRoute: uiItemsRoute,
  uiUnitsRoute: uiUnitsRoute,
  uiIndexRoute: uiIndexRoute,
}

const uiRouteRouteWithChildren =
  uiRouteRoute._addFileChildren(uiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  uiRouteRoute: uiRouteRouteWithChildren,
  ApiActionRoute: ApiActionRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSseRoute: ApiSseRoute,
  IconSplatRoute: IconSplatRoute,
  ApiStatusChar123HashChar125Route: ApiStatusChar123HashChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
