/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IconDotChar123extChar125RouteImport } from './routes/icon[.]{$ext}'
import { Route as uiRouteRouteImport } from './routes/(ui)/route'
import { Route as uiIndexRouteImport } from './routes/(ui)/index'
import { Route as ApiSseRouteImport } from './routes/api/sse'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as uiUnitsRouteImport } from './routes/(ui)/units'
import { Route as uiSchedulesRouteImport } from './routes/(ui)/schedules'
import { Route as uiItemsRouteImport } from './routes/(ui)/items'
import { Route as uiCategoriesRouteImport } from './routes/(ui)/categories'

const IconDotChar123extChar125Route =
  IconDotChar123extChar125RouteImport.update({
    id: '/icon.{$ext}',
    path: '/icon.{$ext}',
    getParentRoute: () => rootRouteImport,
  } as any)
const uiRouteRoute = uiRouteRouteImport.update({
  id: '/(ui)',
  getParentRoute: () => rootRouteImport,
} as any)
const uiIndexRoute = uiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => uiRouteRoute,
} as any)
const ApiSseRoute = ApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const uiUnitsRoute = uiUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiSchedulesRoute = uiSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiItemsRoute = uiItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => uiRouteRoute,
} as any)
const uiCategoriesRoute = uiCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => uiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/icon.{$ext}': typeof IconDotChar123extChar125Route
  '/categories': typeof uiCategoriesRoute
  '/items': typeof uiItemsRoute
  '/schedules': typeof uiSchedulesRoute
  '/units': typeof uiUnitsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/': typeof uiIndexRoute
}
export interface FileRoutesByTo {
  '/icon.{$ext}': typeof IconDotChar123extChar125Route
  '/categories': typeof uiCategoriesRoute
  '/items': typeof uiItemsRoute
  '/schedules': typeof uiSchedulesRoute
  '/units': typeof uiUnitsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/': typeof uiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(ui)': typeof uiRouteRouteWithChildren
  '/icon.{$ext}': typeof IconDotChar123extChar125Route
  '/(ui)/categories': typeof uiCategoriesRoute
  '/(ui)/items': typeof uiItemsRoute
  '/(ui)/schedules': typeof uiSchedulesRoute
  '/(ui)/units': typeof uiUnitsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/sse': typeof ApiSseRoute
  '/(ui)/': typeof uiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/icon.{$ext}'
    | '/categories'
    | '/items'
    | '/schedules'
    | '/units'
    | '/api/ping'
    | '/api/sse'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/icon.{$ext}'
    | '/categories'
    | '/items'
    | '/schedules'
    | '/units'
    | '/api/ping'
    | '/api/sse'
    | '/'
  id:
    | '__root__'
    | '/(ui)'
    | '/icon.{$ext}'
    | '/(ui)/categories'
    | '/(ui)/items'
    | '/(ui)/schedules'
    | '/(ui)/units'
    | '/api/ping'
    | '/api/sse'
    | '/(ui)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  uiRouteRoute: typeof uiRouteRouteWithChildren
  IconDotChar123extChar125Route: typeof IconDotChar123extChar125Route
  ApiPingRoute: typeof ApiPingRoute
  ApiSseRoute: typeof ApiSseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/icon.{$ext}': {
      id: '/icon.{$ext}'
      path: '/icon.{$ext}'
      fullPath: '/icon.{$ext}'
      preLoaderRoute: typeof IconDotChar123extChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ui)': {
      id: '/(ui)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof uiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ui)/': {
      id: '/(ui)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof uiIndexRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/api/sse': {
      id: '/api/sse'
      path: '/api/sse'
      fullPath: '/api/sse'
      preLoaderRoute: typeof ApiSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ui)/units': {
      id: '/(ui)/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof uiUnitsRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/schedules': {
      id: '/(ui)/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof uiSchedulesRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/items': {
      id: '/(ui)/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof uiItemsRouteImport
      parentRoute: typeof uiRouteRoute
    }
    '/(ui)/categories': {
      id: '/(ui)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof uiCategoriesRouteImport
      parentRoute: typeof uiRouteRoute
    }
  }
}

interface uiRouteRouteChildren {
  uiCategoriesRoute: typeof uiCategoriesRoute
  uiItemsRoute: typeof uiItemsRoute
  uiSchedulesRoute: typeof uiSchedulesRoute
  uiUnitsRoute: typeof uiUnitsRoute
  uiIndexRoute: typeof uiIndexRoute
}

const uiRouteRouteChildren: uiRouteRouteChildren = {
  uiCategoriesRoute: uiCategoriesRoute,
  uiItemsRoute: uiItemsRoute,
  uiSchedulesRoute: uiSchedulesRoute,
  uiUnitsRoute: uiUnitsRoute,
  uiIndexRoute: uiIndexRoute,
}

const uiRouteRouteWithChildren =
  uiRouteRoute._addFileChildren(uiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  uiRouteRoute: uiRouteRouteWithChildren,
  IconDotChar123extChar125Route: IconDotChar123extChar125Route,
  ApiPingRoute: ApiPingRoute,
  ApiSseRoute: ApiSseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
